version: '3.7'
services:
  db:
    container_name: tetris_db
    image: postgres
    volumes:
      - tetris_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=tetris
      - POSTGRES_USER=tetris
      - POSTGRES_DB=tetris
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432

volumes:
  tetris_db: {}
