version: "3.7"
services:
  postgres_db:
    image: postgres
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: tetris
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    image: tetris
    depends_on:
      - postgres_db
    ports:
      - "8080:8080"