version: "3.7"
services:
  postgres_db:
    image: postgres
    environment:
      POSTGRES_USER: tetris
      POSTGRES_PASSWORD: tetris
      POSTGRES_DB: tetris
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  web:
    image: tetris
    depends_on:
      - postgres_db
    ports:
      - "80:8080"
      - "443:8443"