spring:
  profiles:
    active: integration
  datasource:
    url: jdbc:postgresql://localhost:5433/tetris_test
    username: tetris_test
    password: tetris_test
  jpa:
    hibernate:
      ddl-auto: validate