#Used for deploy on an E2C instance via Docker-compose
spring:
  datasource:
    url: jdbc:postgresql://postgres_db:5432/tetris
    username: tetris
    password: tetris
  jpa:
    hibernate:
      ddl-auto: validate
security:
  require-ssl: true
server:
  ssl:
    key-store: /etc/letsencrypt/live/demo.zfz7.org/keystore.p12
    key-store-password: tetris
    keyStoreType: PKCS12
    keyAlias: tomcat