name: Gradle Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      tetris_db:
        image: postgres
        env:
          POSTGRES_PASSWORD: tetris
          POSTGRES_USER: tetris
          POSTGRES_DB: tetris
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Run tests
        run: ./gradlew test

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.6.8
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "tetris-demo-gains"
          heroku_email: ${{secrets.HEROKU_EMIAL}}
          branch: "main"